// <auto-generated />
using System;
using InternSystem.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InternSystem.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InternSystem.Core.Entities.ActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Metadata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PerformedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("TargetInternId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("TargetInternId");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DistanceMeters")
                        .HasColumnType("float");

                    b.Property<double>("FaceConfidence")
                        .HasColumnType("float");

                    b.Property<bool>("FaceVerified")
                        .HasColumnType("bit");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInRange")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<bool>("LivenessVerified")
                        .HasColumnType("bit");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InternId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Certificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByMentorId")
                        .HasColumnType("int");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("LanguagesUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MentorProjectNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PdfPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProjectOutcomes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByMentorId");

                    b.HasIndex("InternId");

                    b.ToTable("Certificates");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RadiusMeters")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "ERP",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 24.894995000000002,
                            Longitude = 67.152181999999996,
                            Name = "ERP Section",
                            RadiusMeters = 30.0
                        },
                        new
                        {
                            Id = 2,
                            Code = "CYBER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            Latitude = 24.894427,
                            Longitude = 67.151781999999997,
                            Name = "Cyber Security",
                            RadiusMeters = 30.0
                        });
                });

            modelBuilder.Entity("InternSystem.Core.Entities.GatePass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByMentorId")
                        .HasColumnType("int");

                    b.Property<string>("CnicImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("PdfPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByMentorId");

                    b.HasIndex("InternId");

                    b.ToTable("GatePasses");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.IdCardRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByMentorId")
                        .HasColumnType("int");

                    b.Property<string>("CnicImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("PdfPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentIdImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByMentorId");

                    b.HasIndex("InternId");

                    b.ToTable("IdCardRequests");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Intern", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Degree")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaceEmbeddingJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FaceEnrolled")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MentorId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("University")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("MentorId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Interns");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.InternTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedByMentorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InternId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByMentorId");

                    b.HasIndex("InternId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Mentor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByAdminId")
                        .HasColumnType("int");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsActive = true,
                            PasswordHash = "$2a$11$L6VjsXyoFJyhMQHw02FMrekMGpQTDgtSKF3Ee8KfwwoYaCP67Be/S",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("InternSystem.Core.Entities.ActivityLog", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.User", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.Intern", "TargetIntern")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("TargetInternId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("PerformedByUser");

                    b.Navigation("TargetIntern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Attendance", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany("Attendances")
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Certificate", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Mentor", "ApprovedByMentor")
                        .WithMany()
                        .HasForeignKey("ApprovedByMentorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany("Certificates")
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByMentor");

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.GatePass", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Mentor", "ApprovedByMentor")
                        .WithMany()
                        .HasForeignKey("ApprovedByMentorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany("GatePasses")
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByMentor");

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.IdCardRequest", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Mentor", "ApprovedByMentor")
                        .WithMany()
                        .HasForeignKey("ApprovedByMentorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany()
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedByMentor");

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Intern", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Department", "Department")
                        .WithMany("Interns")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.Mentor", "Mentor")
                        .WithMany("Interns")
                        .HasForeignKey("MentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.User", "User")
                        .WithOne("Intern")
                        .HasForeignKey("InternSystem.Core.Entities.Intern", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Mentor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.InternTask", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Mentor", "AssignedByMentor")
                        .WithMany()
                        .HasForeignKey("AssignedByMentorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.Intern", "Intern")
                        .WithMany("Tasks")
                        .HasForeignKey("InternId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByMentor");

                    b.Navigation("Intern");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Mentor", b =>
                {
                    b.HasOne("InternSystem.Core.Entities.Department", "Department")
                        .WithMany("Mentors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InternSystem.Core.Entities.User", "User")
                        .WithOne("Mentor")
                        .HasForeignKey("InternSystem.Core.Entities.Mentor", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Department", b =>
                {
                    b.Navigation("Interns");

                    b.Navigation("Mentors");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Intern", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("Attendances");

                    b.Navigation("Certificates");

                    b.Navigation("GatePasses");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.Mentor", b =>
                {
                    b.Navigation("Interns");
                });

            modelBuilder.Entity("InternSystem.Core.Entities.User", b =>
                {
                    b.Navigation("Intern");

                    b.Navigation("Mentor");
                });
#pragma warning restore 612, 618
        }
    }
}
